version: 2
updates:
  # Python 패키지 업데이트
  - package-ecosystem: "pip"
    directory: "/benchmark-deployer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(benchmark-deployer)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "benchmark-deployer"

  - package-ecosystem: "pip"
    directory: "/benchmark-manager"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(benchmark-manager)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "benchmark-manager"

  - package-ecosystem: "pip"
    directory: "/benchmark-results"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(benchmark-results)"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "benchmark-results"

  # Docker 이미지 업데이트
  - package-ecosystem: "docker"
    directory: "/benchmark-deployer"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/benchmark-manager"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:15"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/benchmark-results"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions 업데이트
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "auto-merge" 