apiVersion: v1
kind: Secret
metadata:
  name: benchmark-shared-secrets
type: Opaque
stringData:
  MONGO_URL: ""
  
  # Base64 encoded GitHub token  
  # To set: echo -n "your_github_token_here" | base64
  GITHUB_TOKEN: ""