# 테스트 시나리오 4: GPU 리소스 충돌 테스트
model_name: "microsoft/DialoGPT-small"
gpu_memory_utilization: 0.1
max_num_seqs: 16
block_size: 8
tensor_parallel_size: 1
pipeline_parallel_size: 1
trust_remote_code: false
dtype: "auto"
max_model_len: 512
quantization: null
served_model_name: "test-gpu-model"
port: 8002
host: "0.0.0.0"
gpu_resource_type: "nvidia.com/gpu"
gpu_resource_count: 1
additional_args:
  disable-log-stats: true 