# MacBook 환경 전용 vLLM 설정
# 제한된 리소스 환경에서 테스트하기 위한 설정

model_name: "microsoft/DialoGPT-small"
gpu_memory_utilization: 0.1
max_num_seqs: 16
block_size: 8
tensor_parallel_size: 1
pipeline_parallel_size: 1
trust_remote_code: false
dtype: "auto"
max_model_len: 512
quantization: null
served_model_name: null
port: 8000
host: "0.0.0.0"

# GPU 리소스 설정 (MacBook 테스트용 - 실제로는 할당되지 않음)
gpu_resource_type: "cpu"
gpu_resource_count: 0

# 추가 설정 (메모리 사용량 최소화)
additional_args:
  disable-log-stats: true
  disable-log-requests: true

# 다른 테스트 시나리오들:
#
# MIG 리소스 테스트:
# gpu_resource_type: "nvidia.com/mig-3g.20gb"
# gpu_resource_count: 1
#
# 다중 GPU 테스트:
# gpu_resource_type: "nvidia.com/gpu"
# gpu_resource_count: 2
#
# 더 큰 모델 (리소스 충분한 경우):
# model_name: "microsoft/DialoGPT-medium"
# max_num_seqs: 32
# max_model_len: 1024 